/*
 * TMS9918B reference model - TMS9918B report generator
 *
 * Copyright 2026 Saverio Russo
 * SPDX-License-Identifier: Apache-2.0
 *
 * Writes docs/generated/{calendars,dram_timing,cpu_timing}.md from the model.
 *
 * g++ -std=c++17 -O2 -I../src -Isrc/tms99xx tms9918b_report.cpp \
 *     ../src/TMS9918BCalendar.cpp ../src/TMS9918BAnalysis.cpp ../src/tms99xx/TMS99xxVramSlotSchedule.cpp
 * ./a.out <output directory>
 */

#include "TMS9918BAnalysis.h"
#include "TMS9918BCalendar.h"
#include "TMS9918BTiming.h"

#include <cstdio>
#include <string>

using namespace TMS9918B;

static const char* TmsActivityName(TMS99xxVramSlotSchedule::Activity a)
{
    using A = TMS99xxVramSlotSchedule::Activity;
    switch (a)
    {
        case A::Cpu: return "CPU";
        case A::Refresh: return "refresh";
        case A::Name: return "name";
        case A::Colour: return "colour";
        case A::Pattern: return "pattern";
        case A::SpriteScanY: return "sprite Y scan";
        case A::SpriteSelectedY: return "selected sprite Y";
        case A::SpriteSelectedX: return "selected sprite X";
        case A::SpriteSelectedName: return "selected sprite name";
        case A::SpriteSelectedColour: return "selected sprite colour";
        case A::SpriteSelectedPattern: return "selected sprite pattern";
        default: return "?";
    }
}

static std::string Label(const Cycle& c)
{
    if (c.kind == Kind::TmsSlot)
    {
        char buf[64];
        std::snprintf(buf, sizeof buf, "%s %u", TmsActivityName(c.tmsActivity), c.index);
        return buf;
    }
    return CycleLabel(c);
}

static void WriteCalendars(const std::string& dir)
{
    FILE* f = std::fopen((dir + "/calendars.md").c_str(), "w");
    std::fprintf(f, "# TMS9918B VRAM calendars (generated)\n\n");
    std::fprintf(f, "Generated by `tools/tms9918b_report.cpp`. Unit = half period of the 10.738635 MHz crystal (%.2f ns); "
                    "a line is 1368 units; unit = 2 x TMS99xx phase; TMS99xx slot s starts at unit (8s + 1364) mod 1368. "
                    "Start = RAS falling edge. An n-byte cycle lasts 5n + 2 units; byte k is sampled at start + 4 + 5k. "
                    "Units above 1367 belong to the next line's numbering (start - 1368).\n\n", NanosecondsPerUnit);

    std::fprintf(f, "## Templates\n\n");
    std::fprintf(f, "### Tiles (Graphics1X, Graphics2Fat), cell pair p, base = 212 + 64p\n\n"
                    "| Offset | Length | Bytes | Read | Sampled at |\n|---|---|---|---|---|\n"
                    "| +0 | 12 | 2 | name, attribute of cell 2p | +4, +9 |\n"
                    "| +12 | 7 | 1 | sprite Y (sprite p on even lines, 16+p on odd lines) | +16 |\n"
                    "| +19 | 12 | 2 | pattern row of cell 2p (stratum 0, 1) | +23, +28 |\n"
                    "| +31 | 12 | 2 | name, attribute of cell 2p+1 | +35, +40 |\n"
                    "| +43 | 7 | 1 | CPU | - |\n"
                    "| +50 | 12 | 2 | pattern row of cell 2p+1 | +54, +59 |\n"
                    "| +62 | 2 | - | idle | - |\n\n");
    std::fprintf(f, "### Bitmap (Bitmap, BitmapQ), cell pair p, base = 212 + 64p\n\n"
                    "| Offset | Length | Bytes | Read | Sampled at |\n|---|---|---|---|---|\n"
                    "| +0 | 22 | 4 | bitmap bytes of cells 2p, 2p+1 | +4, +9, +14, +19 |\n"
                    "| +22 | 7 | 1 | CPU | - |\n"
                    "| +29 | 12 | 2 | palette map of areas 2p, 2p+1 | +33, +38 |\n"
                    "| +41 | 7 | 1 | sprite Y | +45 |\n"
                    "| +48 | 7 | 1 | CPU | - |\n"
                    "| +55 | 9 | - | idle | - |\n\n");
    std::fprintf(f, "### Text40 (Text40X, Text40XQ), column pair q, base = 236 + 48q\n\n"
                    "| Offset | Length | Bytes | Read | Sampled at |\n|---|---|---|---|---|\n"
                    "| +0 | 22 | 4 | character, colour of columns 2q, 2q+1 | +4, +9, +14, +19 |\n"
                    "| +22 | 7 | 1 | CPU | - |\n"
                    "| +29 | 7 | 1 | pattern row of column 2q | +33 |\n"
                    "| +36 | 7 | 1 | pattern row of column 2q+1 | +40 |\n"
                    "| +43 | 5 | - | idle | - |\n\n");
    std::fprintf(f, "### Text64, column group g (4 columns), base = 212 + 64g\n\n"
                    "| Offset | Length | Bytes | Read | Sampled at |\n|---|---|---|---|---|\n"
                    "| +0 | 22 | 4 | names of columns 4g..4g+3 | +4, +9, +14, +19 |\n"
                    "| +22 | 7 | 1 | CPU | - |\n"
                    "| +29 | 7 | 1 | pattern row of column 4g | +33 |\n"
                    "| +36 | 7 | 1 | pattern row of column 4g+1 | +40 |\n"
                    "| +43 | 7 | 1 | pattern row of column 4g+2 | +47 |\n"
                    "| +50 | 7 | 1 | pattern row of column 4g+3 | +54 |\n"
                    "| +57 | 7 | 1 | CPU | - |\n\n");
    std::fprintf(f, "### Horizontal blanking of Tiles and Bitmap, units 1236-1579\n\n"
                    "CPU; then for channel pairs (0,1) (2,3) (4,5) (6,7): SAT X|name|colour of a (17), of b (17), CPU, "
                    "left half a, right half a, left half b, right half b, CPU (76 units each); then 4 CPU cycles; "
                    "units 1575-1579 idle.\n\n");

    for (CalendarId id : AllCalendars())
    {
        const Calendar& c = GetCalendar(id);
        std::fprintf(f, "## %s\n\n", c.name);
        if (c.id == CalendarId::TmsRefresh || c.id == CalendarId::TmsGraphics || c.id == CalendarId::TmsText ||
            c.id == CalendarId::TmsMulticolor)
        {
            std::fprintf(f, "TMS9918A calendar: one 7-unit cycle at the start of each of the 171 slots (unit 8s + 1364 mod 1368), "
                            "then 1 idle unit. CPU cycles at units:");
            for (std::uint16_t u : CpuRasUnits(c)) std::fprintf(f, " %u", u);
            std::fprintf(f, "\n\n");
            continue;
        }
        std::fprintf(f, "| # | Start (unit) | End (unit) | Start (ns from phase 0) | Bytes | Read |\n|---|---|---|---|---|---|\n");
        int i = 0;
        for (const Cycle& cy : c.cycles)
            std::fprintf(f, "| %d | %u | %u | %.1f | %u | %s |\n", i++, cy.start, cy.End(), Ns(cy.start), cy.bytes, Label(cy).c_str());
        std::fprintf(f, "\nCPU cycles per line: %zu\n\n", CpuRasUnits(c).size());
    }

    std::fprintf(f, "## 80 versus 64 columns\n\n80 columns of 6x8 characters (12 units each) need, every 4 columns, one 4-byte name cycle "
                    "(22 units) and 4 pattern bytes (4 x 7 units): 50 units in 48. Pattern bytes of different characters are not "
                    "adjacent, so no burst can merge them: 80 columns are not available. 64 columns of 8x8 characters (16 units each) "
                    "give 64 units per group: 50 units of reads plus two CPU cycles (Text64).\n");
    std::fclose(f);
}

static void WriteDram(const std::string& dir)
{
    FILE* f = std::fopen((dir + "/dram_timing.md").c_str(), "w");
    std::fprintf(f, "# TMS9918B VRAM cycles against DRAM data sheets (generated)\n\n");
    std::fprintf(f, "VDP assumptions: RD bus setup %.0f ns before the CAS rising edge, board delay budget %.0f ns "
                    "(strobe out plus data back), unit %.2f ns.\n\n", VdpDataSetupNs, SystemDelayNs, NanosecondsPerUnit);
    std::fprintf(f, "Waveform of an n-byte cycle: RAS low [0, 5n-1), precharge 3 units; CAS for byte k low [1+5k, 4+5k); "
                    "single-byte writes are late writes: WE low [2, 4), data on AD after the column address.\n\n");
    for (const DramSpec* d : {&MB8118_12, &MCM4517_12, &MCM4517_15})
    {
        std::fprintf(f, "## %s\n\n", d->name);
        for (std::uint8_t n = 1; n <= 4; ++n)
        {
            const auto checks = VerifyRead(*d, n);
            std::fprintf(f, "### Read, %u byte%s (%u units): %s\n\n| Parameter | Required (ns) | Provided (ns) | Margin (ns) |\n|---|---|---|---|\n",
                         n, n > 1 ? "s" : "", CycleUnits(n), AllOk(checks) ? "PASS" : "FAIL");
            for (const Check& k : checks)
                std::fprintf(f, "| %s | %.1f | %.1f | %s%.1f |\n", k.parameter.c_str(), k.required, k.actual, k.Ok() ? "" : "**", k.Margin());
            std::fprintf(f, "\n");
        }
        const auto w = VerifyWrite(*d);
        std::fprintf(f, "### Write, 1 byte: %s\n\n| Parameter | Required (ns) | Provided (ns) | Margin (ns) |\n|---|---|---|---|\n", AllOk(w) ? "PASS" : "FAIL");
        for (const Check& k : w)
            std::fprintf(f, "| %s | %.1f | %.1f | %.1f |\n", k.parameter.c_str(), k.required, k.actual, k.Margin());
        std::fprintf(f, "\n");
    }
    std::fclose(f);
}

static void WriteCpu(const std::string& dir)
{
    FILE* f = std::fopen((dir + "/cpu_timing.md").c_str(), "w");
    std::fprintf(f, "# TMS9918B CPU to VDP access times (generated)\n\n");
    std::fprintf(f, "Rules of GearSF7000's TMS99xxVramSequencer in units: 44-unit port latency (2 us), issue on the next CPU cycle, "
                    "newer write replaces a waiting one. Z80 at 3.58 MHz: 1 T-state = 6 units.\n\n");
    std::fprintf(f, "| Condition | Mode | VDP delay | Time waiting for an access window | Total time | Total T-states @ 3.58 MHz |\n|---|---|---|---|---|---|\n");
    struct Row { const char* condition; const char* mode; CalendarId id; Region region; };
    const Row rows[] = {
        {"Active display area", "Text (TMS)", CalendarId::TmsText, Region::ActiveArea},
        {"Active display area", "Graphics I, II (TMS)", CalendarId::TmsGraphics, Region::ActiveArea},
        {"Active display area", "Multicolor (TMS)", CalendarId::TmsMulticolor, Region::ActiveArea},
        {"Whole line", "Graphics1X, Graphics2Fat", CalendarId::Tiles, Region::WholeLine},
        {"Whole line", "Bitmap, BitmapQ", CalendarId::Bitmap, Region::WholeLine},
        {"Whole line", "Text40X, Text40XQ", CalendarId::Text40, Region::WholeLine},
        {"Whole line", "Text64, Text64Q", CalendarId::Text64, Region::WholeLine},
    };
    for (const Row& r : rows)
    {
        const Latency l = WorstLatency(GetCalendar(r.id), r.region);
        std::fprintf(f, "| %s | %s | 2 us | 0 - %.2f us | 2 - %.2f us | %u |\n", r.condition, r.mode, Ns(l.waitUnits) / 1000.0,
                     l.microseconds, l.tStates);
    }
    std::fprintf(f, "| 4300 us after vertical interrupt | All | 2 us | 0 us | 2 us | 8 |\n| Register 1 blank bit 0 | All | 2 us | 0 us | 2 us | 8 |\n\n");

    std::fprintf(f, "## Writes lost by continuous loops\n\n| Calendar | CPU cycles | OUTI chain (16 T) | OUTI+NOP (20 T) | OTIR (21 T) | OUTI+2 NOP (24 T) | OUTI+JR NZ (28 T) |\n|---|---|---|---|---|---|---|\n");
    for (CalendarId id : {CalendarId::TmsGraphics, CalendarId::TmsMulticolor, CalendarId::TmsText, CalendarId::Tiles, CalendarId::Bitmap, CalendarId::Text40, CalendarId::Text64})
    {
        const Calendar& c = GetCalendar(id);
        const auto cpu = CpuRasUnits(c);
        std::fprintf(f, "| %s | %zu | %.1f%% | %.1f%% | %.1f%% | %.1f%% | %.1f%% |\n", c.name, cpu.size(), LossPercent(cpu, 96),
                     LossPercent(cpu, 120), LossPercent(cpu, 126), LossPercent(cpu, 144), LossPercent(cpu, 168));
    }
    std::fclose(f);
}

int main(int argc, char** argv)
{
    const std::string dir = argc > 1 ? argv[1] : ".";
    WriteCalendars(dir);
    WriteDram(dir);
    WriteCpu(dir);
    std::printf("written %s/{calendars,dram_timing,cpu_timing}.md\n", dir.c_str());
    return 0;
}
